{
 "title": "Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "_statistics_",
     "rawSql": "-- SELECT * FROM transaction JOIN click_stream ON transaction.session_id = click_stream.session_id;\r\n\r\nSELECT * FROM click_stream WHERE session_id = \"01fdaea1-f338-462b-b95d-6d240522edfd\"\r\nSELECT * FROM transaction WHERE session_id = \"01fdaea1-f338-462b-b95d-6d240522edfd\"\r\n"
    }
   ]
  },
  {
   "title": "Hành vi người dùng theo thời gian trong ngày",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "_statistics_",
     "rawSql": "SELECT HOUR(event_time) AS hour, COUNT(*) AS total_events\r\nFROM click_stream\r\nGROUP BY hour\r\nORDER BY hour;"
    }
   ]
  },
  {
   "title": "Số sự kiện click theo traffic source",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "_statistics_",
     "rawSql": "SELECT traffic_source, COUNT(*) AS event_count\r\nFROM click_stream\r\nGROUP BY traffic_source;"
    }
   ]
  },
  {
   "title": "Heatmap: Thiết bị theo giới tính người dùng",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "_statistics_",
     "rawSql": "SELECT gender, device_type, COUNT(*) AS count\r\nFROM customer\r\nGROUP BY gender, device_type;"
    }
   ]
  },
  {
   "title": "Total customers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "_statistics_", "rawSql": "SELECT COUNT(*) FROM customer;" }
   ]
  },
  {
   "title": "Total click_streams",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "_statistics_",
     "rawSql": "SELECT COUNT(*) FROM click_stream;"
    }
   ]
  },
  {
   "title": "Total products",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "_statistics_", "rawSql": "SELECT COUNT(*) FROM product;" }
   ]
  },
  {
   "title": "Total transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "_statistics_",
     "rawSql": "SELECT COUNT(*) FROM transaction;"
    }
   ]
  },
  {
   "title": "Thống kê loại thiết bị người dùng sử dụng",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "_statistics_",
     "rawSql": "SELECT device_type, COUNT(*) AS user_count\r\nFROM customer\r\nGROUP BY device_type;"
    }
   ]
  }
 ]
}