---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: kafka-internal
      port: 29092
      targetPort: 29092
  selector:
    app: redpanda
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: redpanda-console
  type: ClusterIP