apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: starrocks
spec:
  ports:
    - protocol: TCP
      port: 9000
      name: api
      targetPort: 9000
    - protocol: TCP
      port: 9001
      name: console
      targetPort: 9001
  selector:
    app: minio
  type: NodePort