apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: starrocks

resources:
  - namespace.yaml
  - starrocks/starrocks-fe-and-be.yaml

  - grafana/deployment.yaml
  - grafana/service.yaml
  
  - ingress.yaml

