apiVersion: apps/v1
kind: Deployment
metadata:
  name: starrocks-cn
  namespace: starrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starrocks-cn
  template:
    metadata:
      labels:
        app: starrocks-cn
    spec:
      containers:
        - name: starrocks-cn
          image: starrocks/cn-ubuntu:3.1-latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for FE to be ready...";
              ulimit -u 65535;
              ulimit -n 65535;
              for i in {1..10}; do
                if mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "SELECT 1"; then
                  echo "Connected"
                  break;
                fi;
                echo "Retrying in 5s..."; sleep 5;
              done;
              echo "Start creating";
              /opt/starrocks/cn/bin/start_cn.sh
              echo "Created";
              mysql -h starrocks-fe -P9030 -uroot -e "ALTER SYSTEM ADD COMPUTE NODE \"starrocks-cn:9050\";";
              echo "Finish";
          ports:
            - containerPort: 8040
            - containerPort: 9050
          securityContext:
            runAsUser: 0
            privileged: true
            allowPrivilegeEscalation: true
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "2"
