apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
  name: starrockscluster-sample
  namespace: starrocks
spec:
  starRocksFeSpec:
    image: starrocks/fe-ubuntu:latest
    replicas: 1
    storageVolumes:
    - name: fe-meta
      storageSize: 10Gi
      mountPath: /opt/starrocks/fe/meta
    - name: fe-log
      storageSize: 5Gi
      mountPath: /opt/starrocks/fe/log
  starRocksBeSpec:
    image: starrocks/be-ubuntu:latest
    replicas: 1
    storageVolumes:
    - name: be-data
      storageSize: 1Ti
      mountPath: /opt/starrocks/be/storage
    - name: be-log
      storageSize: 1Gi
      mountPath: /opt/starrocks/be/log
